Hrg action44
DryCreations/pdfproject pull request #66
Opened 2021-04-22 23:38 UTC by hgongloff

# List Any Relevant Actions or Tasks

## Actions

Action 44

## Tasks

Task 16.2

# Description of Changes

I added the ability to create radio buttons inside the pdf.

# Relevant Artifacts

Before 
<img width="794" alt="Before" src="https://user-images.githubusercontent.com/47669209/115797625-591c7a00-a3a2-11eb-92f8-53b7482b4f42.PNG">

After
<img width="811" alt="After" src="https://user-images.githubusercontent.com/47669209/115797633-5de12e00-a3a2-11eb-98f4-d25458e60020.PNG">

# Other Comments

Like with action 43, I had to create a new folder inside of resources called manipulate_pdf to store both the original and updated pdf. For some reason I could only alter the names of the pdfs if they were not inside the resources folder. Because of this it is not possible to reopen the pdf in our canvas. This could be fixed by having the canvas also use the folder I created for its pdf but I realize this would cause a lot of merge conflicts and might not be an ideal fix.

2021-04-23 00:31 UTC, DryCreations requested changes
Many of these files being deleted should not be deleted (such as the /grading folder) please ensure the only changes you are making are for this action.

2021-04-23 00:32 UTC, bobobo77 reviewed
Where's the grading folder? Without that I believe Buck would be disappointed

2021-04-23 04:09 UTC, DryCreations requested changes
I'm going to leave the same feedback as I did on https://github.com/DryCreations/pdfproject/pull/58

You are not displaying the changes on the pdf canvas, and you are directly modifying the pdf instead. This is not consistent with previous tools. We have been drawing the changes on the canvas, and adding them to an undo stack, and only modifying a pdf whenever we save a docuement.

You may want to look over how `DrawRectangle` is implemented, the `execute` method draws the representation of a rectangle on a canvas, and `pdfExecute` is later used to draw on a pdf when the document is saved.

2021-04-27 06:18 UTC, DryCreations approved these changes

2021-04-29 23:50 UTC, Cassandra-Mae-Patel approved these changes

2021-04-30 00:26 UTC, merged